# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e08caddc327bcdcf8bb4670d0385e2cab1274a2587bc1725741da87ebedb8f5c16bd11c27f491acd3069eaf2a23fd114851b4a27929e7b9985ae699d49f9af9

test:
  secret_key_base: d0f9338bb2daa4bc23ba51ee3dcfa5103df32cdf5a6f8f6f92f2f26ad00c9f627e8f303c09cb59f26b48eff6160cfcdc45310db15b7d19e84dfb52889b339066

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
